---
- name: "Ensure interfaces L2 configuration is {{ l2_interface_state }}"
  net_l2_interface:
    aggregate: "{{ l2_interface_aggregate }}"
    state: "{{ l2_interface_state }}"
  register: r_l2_interface
  tags:
    - l2_interface
