---
- name: "Ensure interface L3 configuration is {{ l3_interface_state }}"
  net_l3_interface:
    aggregate: "{{ l3_interface_aggregate }}"
    state: "{{ l3_interface_state }}"
    purge: "{{ l3_interface_purge }}"
  register: r_l3_interface
  tags:
    - l3_interface
