---
- name: "Ensure net_lldp_interface"
  net_lldp_interface:
    aggregate: "{{ net_lldp_interface.aggregate }}"
    state: "{{ net_lldp_interface.state | default(omit) }}"
    purge: "{{ net_lldp_interface.purge | default(omit) }}"
  when: (net_lldp_interface.aggregate|default([]))|length > 0
  tags:
    - net_lldp_interface
    - lldp_interface
