---
- name: "Ensure net_vrf"
  net_vrf:
    aggregate: "{{ net_vrf.aggregate }}"
    state: "{{ net_vrf.state | default(omit) }}"
    purge: "{{ net_vrf.purge | default(omit) }}"
  when: (net_vrf.aggregate|default([]))|length > 0
  tags:
    - net_vrf
    - vrf
